# Generated by Django 5.0.7 on 2024-07-18 10:03

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Дворняга', max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('N', 'Neither'), ('M', 'Male'), ('F', 'Female')], max_length=20, verbose_name='Пол')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('eye_color', models.CharField(max_length=20, verbose_name='Цвет глаз')),
                ('height', models.FloatField(verbose_name='Рост')),
                ('weight', models.FloatField(help_text='В киллограммах', verbose_name='Вес')),
                ('IQ', models.IntegerField(verbose_name='Показатель интелекта')),
                ('bread', models.BooleanField(verbose_name='Bread')),
            ],
            options={
                'verbose_name': 'Ребенок',
            },
        ),
        migrations.CreateModel(
            name='ClothingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('capital', models.BigIntegerField(db_comment='По последним данным', verbose_name='Капитал')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Компания одежды',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('groupe_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MyPersonSlave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('birth', models.DateField(help_text='Укажите в формате ДД.ММ.ГГГГ', verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('N', 'Neither'), ('M', 'Male'), ('F', 'Female')], max_length=20, verbose_name='Пол')),
            ],
            options={
                'proxy': False,
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('address', models.CharField(max_length=30, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Парк',
                'verbose_name_plural': 'Парки',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('data', models.JSONField(verbose_name='Данные')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Soul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_color', models.CharField(choices=[('Bol', 'Лысый'), ('Br', 'Брюнет'), ('Bl', 'Черный'), ('Gi', 'Рыжий')], max_length=20, verbose_name='Цвет волос')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('birth', models.DateField(help_text='Укажите в формате ДД.ММ.ГГГГ', verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('N', 'Neither'), ('M', 'Male'), ('F', 'Female')], max_length=20, verbose_name='Пол')),
                ('grade', models.CharField(max_length=15, verbose_name='Степень')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('something', models.TextField(null=True, verbose_name='Текстовое поле')),
                ('value', models.IntegerField(blank=True, verbose_name='Некое значение')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s', to='core.firstmodel')),
            ],
            options={
                'db_table': 'default',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_number', models.IntegerField(verbose_name='Номер по списку')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='группа', to='core.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Кличка')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Порода', to='core.breed', verbose_name='Собака')),
                ('park', models.ManyToManyField(related_name='Парк', to='core.park', verbose_name='Собака')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('birth', models.DateField(help_text='Укажите в формате ДД.ММ.ГГГГ', verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('N', 'Neither'), ('M', 'Male'), ('F', 'Female')], max_length=20, verbose_name='Пол')),
                ('avatar', models.ImageField(upload_to='media/', verbose_name='Фото')),
                ('group', models.ManyToManyField(related_name='Группа', through='core.GroupeInfo', to='core.groupe')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.AddField(
            model_name='groupeinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='студент', to='core.student'),
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=20, verbose_name='Размер')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Производитель', to='core.clothingcompany', verbose_name='Футболки')),
            ],
            options={
                'verbose_name': 'Футболка',
                'verbose_name_plural': 'Футболки',
            },
        ),
    ]
