# Generated by Django 5.0.7 on 2024-07-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Ребенок', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelOptions(
            name='clothingcompany',
            options={'verbose_name': 'Компания одежды', 'verbose_name_plural': 'Компании одежды'},
        ),
        migrations.AlterField(
            model_name='child',
            name='bread',
            field=models.BooleanField(verbose_name='Борода'),
        ),
        migrations.AlterField(
            model_name='child',
            name='patronymic',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('N', 'Neither'), ('F', 'Female')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='clothingcompany',
            name='capital',
            field=models.BigIntegerField(db_comment='По последним данным', null=True, verbose_name='Капитал'),
        ),
        migrations.AlterField(
            model_name='firstmodel',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s', to='core.firstmodel'),
        ),
        migrations.AlterField(
            model_name='firstmodel',
            name='something',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовое поле'),
        ),
        migrations.AlterField(
            model_name='mypersonslave',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('N', 'Neither'), ('F', 'Female')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(null=True, verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='soul',
            name='hair_color',
            field=models.CharField(choices=[('Bl', 'Черный'), ('Bol', 'Лысый'), ('Br', 'Брюнет'), ('Gi', 'Рыжий')], max_length=20, verbose_name='Цвет волос'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('N', 'Neither'), ('F', 'Female')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('N', 'Neither'), ('F', 'Female')], max_length=20, verbose_name='Пол'),
        ),
    ]
